name: Generate update.json on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get latest release info
        run: |
          LATEST_TAG="${{ github.event.release.tag_name }}"
          VERSION_CODE=$(date +%s)
          ZIP_URL="https://github.com/${{ github.repository }}/releases/download/${LATEST_TAG}/DVTMOD-ZYGISK.zip"
          CHANGELOG="https://raw.githubusercontent.com/${{ github.repository }}/main/README.md"

          echo "{
            \"version\": \"${LATEST_TAG}\",
            \"versionCode\": ${VERSION_CODE},
            \"zipUrl\": \"${ZIP_URL}\",
            \"changelog\": \"${CHANGELOG}\"
          }" > update.json

      - name: Commit and push update.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main  # Đảm bảo checkout đúng nhánh
          git add update.json
          git commit -m "Update update.json for $LATEST_TAG" || exit 0
          git push origin main
