name: Update JSON on Release

on:
  release:
    types: [created, edited, deleted, published, unpublished, prereleased, released]

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate update.json
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION_CODE=$(git rev-list --count HEAD)
          ZIP_URL="https://github.com/dvtlive/ZYGISK-AOV-AUTO-UPDATE/releases/download/${VERSION}/DVTMOD-ZYGISK-${VERSION}.zip"
          CHANGELOG="${{ github.event.release.body }}"

          jq -n \
            --arg version "$VERSION" \
            --argjson versionCode "$VERSION_CODE" \
            --arg zipUrl "$ZIP_URL" \
            --arg changelog "$CHANGELOG" \
            '{version: $version, versionCode: $versionCode, zipUrl: $zipUrl, changelog: $changelog}' > update.json

      - name: Commit and push update.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add update.json
          # Commit trước để làm sạch index
          git diff --staged --quiet || git commit -m "Stage update.json for release ${{ github.event.release.tag_name }}"
          # Pull với rebase sau khi đã commit
          git pull --rebase origin main
          # Push kết quả lên remote
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
