name: Update JSON on Release

on:
  release:
    types: [created, edited, deleted, published, unpublished, prereleased, released]

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog.txt and update.json
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION_CODE=$(git rev-list --count HEAD)
          ZIP_URL="https://github.com/dvtlive/ZYGISK-AOV-AUTO-UPDATE/releases/download/${VERSION}/DVTMOD-ZYGISK-${VERSION}.zip"
          CHANGELOG_URL="https://raw.githubusercontent.com/dvtlive/ZYGISK-AOV-AUTO-UPDATE/refs/heads/main/changelog.txt"

          # Lưu nội dung changelog dạng raw text vào changelog.txt
          echo "${{ github.event.release.body }}" > changelog.txt

          # Tạo update.json với URL trỏ đến changelog.txt
          jq -n \
            --arg version "$VERSION" \
            --argjson versionCode "$VERSION_CODE" \
            --arg zipUrl "$ZIP_URL" \
            --arg changelog "$CHANGELOG_URL" \
            '{version: $version, versionCode: $versionCode, zipUrl: $zipUrl, changelog: $changelog}' > update.json

      - name: Commit and push changelog.txt and update.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add changelog.txt update.json
          git diff --staged --quiet || git commit -m "Update changelog.txt and update.json for release ${{ github.event.release.tag_name }}"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
